data_kurs_default = {
    "AED": {"nama": "Dirham Uni Emirat Arab", "nilai": 4200},
    "AFN": {"nama": "Afghani Afghanistan", "nilai": 210},
    "ALL": {"nama": "Lek Albania", "nilai": 180},
    "AMD": {"nama": "Dram Armenia", "nilai": 40},
    "AOA": {"nama": "Kwanza Angola", "nilai": 20},
    "ARS": {"nama": "Peso Argentina", "nilai": 170},
    "AUD": {"nama": "Dolar Australia", "nilai": 10300},
    "BBD": {"nama": "Dolar Barbados", "nilai": 7500},
    "BDT": {"nama": "Taka Bangladesh", "nilai": 140},
    "BGN": {"nama": "Lev Bulgaria", "nilai": 9000},
    "BHD": {"nama": "Dinar Bahrain", "nilai": 59500},
    "BIF": {"nama": "Franc Burundi", "nilai": 7},
    "BMD": {"nama": "Dolar Bermuda", "nilai": 15000},
    "BND": {"nama": "Dolar Brunei", "nilai": 10900},
    "BOB": {"nama": "Boliviano Bolivia", "nilai": 2200},
    "BRL": {"nama": "Real Brasil", "nilai": 3100},
    "BSD": {"nama": "Dolar Bahama", "nilai": 15000},
    "BTN": {"nama": "Ngultrum Bhutan", "nilai": 180},
    "BWP": {"nama": "Pula Botswana", "nilai": 1200},
    "BYN": {"nama": "Rubel Belarusia", "nilai": 6500},
    "BZD": {"nama": "Dolar Belize", "nilai": 7400},
    "CAD": {"nama": "Dolar Kanada", "nilai": 11200},
    "CHF": {"nama": "Franc Swiss", "nilai": 17500},
    "CLP": {"nama": "Peso Chili", "nilai": 17},
    "CNY": {"nama": "Yuan Cina", "nilai": 2100},
    "COP": {"nama": "Peso Kolombia", "nilai": 38},
    "CRC": {"nama": "Colon Kosta Rika", "nilai": 280},
    "CUP": {"nama": "Peso Kuba", "nilai": 610},
    "CVE": {"nama": "Escudo Tanjung Verde", "nilai": 160},
    "CZK": {"nama": "Koruna Ceko", "nilai": 700},
    "DJF": {"nama": "Franc Djibouti", "nilai": 85},
    "DKK": {"nama": "Krona Denmark", "nilai": 2200},
    "DOP": {"nama": "Peso Dominika", "nilai": 270},
    "DZD": {"nama": "Dinar Aljazair", "nilai": 120},
    "EGP": {"nama": "Pound Mesir", "nilai": 510},
    "ERN": {"nama": "Nakfa Eritrea", "nilai": 1000},
    "ETB": {"nama": "Birr Ethiopia", "nilai": 275},
    "EUR": {"nama": "Euro", "nilai": 16500},
    "FJD": {"nama": "Dolar Fiji", "nilai": 6800},
    "FKP": {"nama": "Pound Kepulauan Falkland", "nilai": 19000},
    "GBP": {"nama": "Poundsterling Inggris", "nilai": 19000},
    "GEL": {"nama": "Lari Georgia", "nilai": 5700},
    "GGP": {"nama": "Pound Guernsey", "nilai": 19000},
    "GHS": {"nama": "Cedi Ghana", "nilai": 1300},
    "GIP": {"nama": "Pound Gibraltar", "nilai": 19000},
    "GMD": {"nama": "Dalasi Gambia", "nilai": 230},
    "GNF": {"nama": "Franc Guinea", "nilai": 1.5},
    "GTQ": {"nama": "Quetzal Guatemala", "nilai": 1900},
    "GYD": {"nama": "Dolar Guyana", "nilai": 720},
    "HKD": {"nama": "Dolar Hong Kong", "nilai": 1950},
    "HNL": {"nama": "Lempira Honduras", "nilai": 620},
    "HRK": {"nama": "Kuna Kroasia", "nilai": 2200},
    "HTG": {"nama": "Gourde Haiti", "nilai": 150},
    "HUF": {"nama": "Forint Hungaria", "nilai": 45},
    "IDR": {"nama": "Rupiah Indonesia", "nilai": 1},
    "ILS": {"nama": "Shekel Israel", "nilai": 4200},
    "IMP": {"nama": "Pound Isle of Man", "nilai": 19000},
    "INR": {"nama": "Rupee India", "nilai": 180},
    "IQD": {"nama": "Dinar Irak", "nilai": 12},
    "IRR": {"nama": "Riyal Iran", "nilai": 0.35},
    "ISK": {"nama": "Krona Islandia", "nilai": 115},
    "JEP": {"nama": "Pound Jersey", "nilai": 19000},
    "JMD": {"nama": "Dolar Jamaika", "nilai": 950},
    "JOD": {"nama": "Dinar Yordania", "nilai": 21200},
    "JPY": {"nama": "Yen Jepang", "nilai": 110},
    "KES": {"nama": "Shilling Kenya", "nilai": 120},
    "KGS": {"nama": "Som Kyrgyzstan", "nilai": 170},
    "KHR": {"nama": "Riel Kamboja", "nilai": 3},
    "KMF": {"nama": "Franc Komoro", "nilai": 35},
    "KPW": {"nama": "Won Korea Utara", "nilai": 8},
    "KRW": {"nama": "Won Korea Selatan", "nilai": 12},
    "KWD": {"nama": "Dinar Kuwait", "nilai": 49500},
    "KYD": {"nama": "Dolar Kepulauan Cayman", "nilai": 18000},
    "KZT": {"nama": "Tenge Kazakhstan", "nilai": 330},
    "LAK": {"nama": "Kip Laos", "nilai": 0.75},
    "LBP": {"nama": "Pound Lebanon", "nilai": 15},
    "LKR": {"nama": "Rupee Sri Lanka", "nilai": 48},
    "LRD": {"nama": "Dolar Liberia", "nilai": 850},
    "LSL": {"nama": "Loti Lesotho", "nilai": 880},
    "LYD": {"nama": "Dinar Libya", "nilai": 3100},
    "MAD": {"nama": "Dirham Maroko", "nilai": 1500},
    "MDL": {"nama": "Leu Moldova", "nilai": 880},
    "MGA": {"nama": "Ariary Madagaskar", "nilai": 3.5},
    "MKD": {"nama": "Denar Makedonia", "nilai": 270},
    "MMK": {"nama": "Kyat Myanmar", "nilai": 7},
    "MNT": {"nama": "Tögrög Mongolia", "nilai": 5},
    "MOP": {"nama": "Pataca Makau", "nilai": 1900},
    "MRU": {"nama": "Ouguiya Mauritania", "nilai": 400},
    "MUR": {"nama": "Rupee Mauritius", "nilai": 340},
    "MVR": {"nama": "Rufiyaa Maladewa", "nilai": 950},
    "MWK": {"nama": "Kwacha Malawi", "nilai": 11},
    "MXN": {"nama": "Peso Meksiko", "nilai": 900},
    "MYR": {"nama": "Ringgit Malaysia", "nilai": 3300},
    "MZN": {"nama": "Metical Mozambik", "nilai": 240},
    "NAD": {"nama": "Dolar Namibia", "nilai": 880},
    "NGN": {"nama": "Naira Nigeria", "nilai": 100},
    "NIO": {"nama": "Córdoba Nikaragua", "nilai": 590},
    "NOK": {"nama": "Krona Norwegia", "nilai": 1550},
    "NPR": {"nama": "Rupee Nepal", "nilai": 120},
    "NZD": {"nama": "Dolar Selandia Baru", "nilai": 9600},
    "OMR": {"nama": "Rial Oman", "nilai": 58000},
    "PAB": {"nama": "Balboa Panama", "nilai": 15000},
    "PEN": {"nama": "Sol Peru", "nilai": 4100},
    "PGK": {"nama": "Kina Papua Nugini", "nilai": 4300},
    "PHP": {"nama": "Peso Filipina", "nilai": 270},
    "PKR": {"nama": "Rupee Pakistan", "nilai": 90},
    "PLN": {"nama": "Zloty Polandia", "nilai": 3900},
    "PYG": {"nama": "Guarani Paraguay", "nilai": 2},
    "QAR": {"nama": "Riyal Qatar", "nilai": 4100},
    "RON": {"nama": "Leu Rumania", "nilai": 3500},
    "RSD": {"nama": "Dinar Serbia", "nilai": 200},
    "RUB": {"nama": "Rubel Rusia", "nilai": 160},
    "RWF": {"nama": "Franc Rwanda", "nilai": 12},
    "SAR": {"nama": "Riyal Saudi", "nilai": 4000},
    "SBD": {"nama": "Dolar Kepulauan Solomon", "nilai": 6600},
    "SCR": {"nama": "Rupee Seychelles", "nilai": 1200},
    "SDG": {"nama": "Pound Sudan", "nilai": 50},
    "SEK": {"nama": "Krona Swedia", "nilai": 1450},
    "SGD": {"nama": "Dolar Singapura", "nilai": 10900},
    "SHP": {"nama": "Pound Saint Helena", "nilai": 19000},
    "SLE": {"nama": "Leone Sierra Leone", "nilai": 100},
    "SOS": {"nama": "Shilling Somalia", "nilai": 30},
    "SRD": {"nama": "Dolar Suriname", "nilai": 5100},
    "SSP": {"nama": "Pound Sudan Selatan", "nilai": 35},
    "STN": {"nama": "Dobra São Tomé", "nilai": 7},
    "SVC": {"nama": "Colon El Salvador", "nilai": 1700},
    "SYP": {"nama": "Pound Suriah", "nilai": 25},
    "SZL": {"nama": "Lilangeni Swaziland", "nilai": 870},
    "THB": {"nama": "Baht Thailand", "nilai": 430},
    "TJS": {"nama": "Somoni Tajikistan", "nilai": 900},
    "TMT": {"nama": "Manat Turkmenistan", "nilai": 4400},
    "TND": {"nama": "Dinar Tunisia", "nilai": 5000},
    "TOP": {"nama": "Paʻanga Tonga", "nilai": 7100},
    "TRY": {"nama": "Lira Turki", "nilai": 490},
    "TZS": {"nama": "Shilling Tanzania", "nilai": 20},
    "UAH": {"nama": "Hryvnia Ukraina", "nilai": 400},
    "UGX": {"nama": "Shilling Uganda", "nilai": 4},
    "USD": {"nama": "Dolar Amerika", "nilai": 15000},
    "UYU": {"nama": "Peso Uruguay", "nilai": 390},
    "UZS": {"nama": "Som Uzbekistan", "nilai": 1.2},
    "VND": {"nama": "Dong Vietnam", "nilai": 0.65},
    "VUV": {"nama": "Vatu Vanuatu", "nilai": 120},
    "WST": {"nama": "Tala Samoa", "nilai": 5900},
    "YER": {"nama": "Riyal Yaman", "nilai": 60},
    "ZAR": {"nama": "Rand Afrika Selatan", "nilai": 850},
    "ZMW": {"nama": "Kwacha Zambia", "nilai": 850},
    "ZWL": {"nama": "Dolar Zimbabwe", "nilai": 5},
}